name: Publish to Packagist

on:
  release:
    types: [published]

jobs:
  update-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update Packagist Package
        run: |
          curl -XPOST -H 'content-type:application/json' \
          "https://packagist.org/api/update-package?username=${{ secrets.PACKAGIST_USERNAME }}&apiToken=${{ secrets.PACKAGIST_TOKEN }}" \
          -d '{"repository":{"url":"https://github.com/${{ github.repository }}"}}'
